version: "3.9"
services:
  web-api:
    build:
      context: .
      dockerfile: src/EmailService.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
      - 3500:8080
      - 5100:8081
    depends_on:
      - postgres
    networks:
      - database

  postgres:
    image: 'postgres:16.1'
    container_name: email-psg
    ports:
      - '5432:5432'
    volumes:
      - 'email-psg:/var/lib/postgresql/data'
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: testPass
      POSTGRES_USER: testUser

networks:
  database:
volumes:
  email-psg:
