@EmailService.Web_HostAddress = https://localhost:7103

GET {{EmailService.Web_HostAddress}}/api/mails
Accept: application/json

###

POST {{EmailService.Web_HostAddress}}/api/mails
Content-Type: application/json

{
  //MailRequest
}

###
